
### SETTINGS ###
SEARCH_DEPTH = 2

GAME_DESTINATION = "Z:\\"
PLEX_LIBRARY = "G:\\TV Shows"
MOVIE_TV_DESTINATION = "Z:\\"
LOG_DESTINATION = "C:\\Users\\mihal\\Desktop"
MUSIC_DESTINATION = "C:\\Users\\mihal\\Desktop"
TORRENT_FOLDER = "H:\\Torrent\\Downloaded Torrents"

MUSIC_CONFIDENCE_REQUIRED_SCORE = 0.40
TV_SEASON_NUM_FILES_REQUIRED = 3
### SETTINGS ###
